addSbtPlugin("com.eed3si9n"	% "sbt-buildinfo"		% "0.5.0")
addSbtPlugin("de.djini"		% "xsbt-webstart"		% "1.7.0")
addSbtPlugin("de.djini"		% "xsbt-scriptstart"	% "1.7.0")
addSbtPlugin("de.djini"		% "xsbt-osxapp"			% "1.8.0")
addSbtPlugin("de.djini"		% "xsbt-capsule"		% "1.9.0")
