addSbtPlugin("com.eed3si9n"	% "sbt-buildinfo"		% "0.3.2")
addSbtPlugin("de.djini"		% "xsbt-webstart"		% "1.5.0")
addSbtPlugin("de.djini"		% "xsbt-scriptstart"	% "1.5.0")
addSbtPlugin("de.djini"		% "xsbt-osxapp"			% "1.5.0")
addSbtPlugin("de.djini"		% "xsbt-capsule"		% "1.5.0")
