addSbtPlugin("org.wartremover"	% "sbt-wartremover"		% "2.2.1")
addSbtPlugin("com.eed3si9n"		% "sbt-buildinfo"		% "0.7.0")
addSbtPlugin("de.djini"			% "xsbt-webstart"		% "2.0.0")
addSbtPlugin("de.djini"			% "xsbt-scriptstart"	% "2.0.0")
addSbtPlugin("de.djini"			% "xsbt-osxapp"			% "2.0.0")
addSbtPlugin("de.djini"			% "xsbt-capsule"		% "2.0.0")
